# Generated by Django 3.0.8 on 2020-07-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200703_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(default=1, verbose_name='Type question, 1 open question, 2 Chosee one, 3 Multiple chosee'),
        ),
    ]
