# Generated by Django 3.0.8 on 2020-07-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200704_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partquestionnaire',
            name='part_questionnaire_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
