# Generated by Django 3.0.8 on 2020-07-07 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_questionnairepart_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='partquestion',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Part'),
        ),
    ]
