# Generated by Django 3.0.8 on 2020-07-15 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_responsequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='choice',
        ),
        migrations.AddField(
            model_name='response',
            name='choice_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='response',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Journey'),
        ),
    ]
