# Generated by Django 3.0.8 on 2020-07-31 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0014_responsecovid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(default='', max_length=300)),
                ('nombre', models.CharField(default='', max_length=300)),
                ('puesto', models.CharField(default='', max_length=300)),
                ('riesgos', models.CharField(default='', max_length=300)),
                ('correo', models.CharField(default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
