# Generated by Django 3.0.8 on 2020-08-01 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0015_infopersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecovid',
            name='date_response',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='responsecovid',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
